# Generated by Django 4.2.28 on 2026-04-03 01:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_privatemessage'),
        ('accounts', '0003_profile_photo_sessionrequest_and_more'),
    ]

    operations = [
    ]
