# Generated by Django 4.2.28 on 2026-03-18 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="skill",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="skill",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"), name="unique_skill_per_user"
            ),
        ),
    ]
